---

env:
  node: true
  es2020: true
  jest: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 2020 # Включает поддержку конструкции import.meta.url
  sourceType: module

rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант
  no-console: 0
  import/extensions: 0
